language: php

php:
    - 7.1
    - 7.2
    - 7.3

cache:
    directories:
        - ~/.composer/cache

before_install:
    - echo '' | pecl upgrade redis
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install

script:
    - php vendor/bin/parallel-lint ./src
    - php vendor/bin/ecs check --verbose ./src ./tests
    - php vendor/bin/phpstan analyze -c ./phpstan.neon ./src --level=4
    - php vendor/bin/phpunit
