#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__ . '/bootstrap.php.cache';
require_once __DIR__ . '/AppKernel.php';
require_once __DIR__ . '/Bootstrap.php';

use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$enviroment = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: ND\Bootstrap::ENVIROMENT_DEVELOPMENT);

$bootstrap = new ND\Bootstrap($enviroment, true);
$bootstrap->run();
