services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\FrameworkBundle\Command\:
        resource: '../../Command'

    Shopsys\FrameworkBundle\Command\ConfigureDomainsUrlsCommand:
        arguments:
            $configFilepath: '%shopsys.domain_urls_config_filepath%'

    Shopsys\FrameworkBundle\Command\ServerRunWithCustomRouterCommand:
        arguments:
            - '%kernel.project_dir%/web'
            - '%kernel.environment%'

    Shopsys\FrameworkBundle\Command\ServerStartWithCustomRouterCommand:
        arguments:
            - '%kernel.project_dir%/web'
            - '%kernel.environment%'

    Shopsys\FrameworkBundle\Command\CreateApplicationDirectoriesCommand:
        arguments:
            $defaultInternalDirectories: '%shopsys.framework.default_internal_directories%'
            $defaultPublicDirectories: '%shopsys.framework.default_public_directories%'
            $internalDirectories: '%internal_directories%'
            $publicDirectories: '%public_directories%'

    Shopsys\FrameworkBundle\Command\GenerateGruntfileCommand:
        arguments:
            - '%shopsys.resources_dir%'
            - '%shopsys.framework.resources_dir%'
            - '%shopsys.root_dir%'

    Shopsys\MigrationBundle\Command\GenerateMigrationCommand:
        arguments:
            - '%shopsys.vendor_dir%'
